services:
    #Repositories
    eventStore\OrderRepository:
        class: Service\Infrastructure\Repository\OrderRepository
        arguments:
            - '@contract_service_event_bus'
            - '@doctrine_mongodb.odm.default_connection'
            - '%env(MONGODB_DB)%'
            - 'event_store'
        public: true

    #GLOBAL
    messagebus_event_global\EventStore:
        class: Service\Infrastructure\Listeners\EventStoreWriter
        arguments: ['@doctrine_mongodb.odm.default_document_manager','%env(MONGODB_DB)%', 'event_store']
        tags:
        - { name: contract_service_event_bus.handler, message: . }

    #COMMAND CUSTOMER
    messagebus_command_order\CreateOrderHandler:
        class: Service\Contract\Model\Order\Handler\CreateOrderHandler
        arguments: ['@eventStore\OrderRepository']
        tags:
        - { name: contract_service_command_bus.handler, message: Service\Contract\Model\Order\Command\CreateOrder }

    messagebus_command_order\ChangeStatusHandler:
        class: Service\Contract\Model\Order\Handler\ChangeStatusHandler
        arguments: ['@eventStore\OrderRepository']
        tags:
        - { name: contract_service_command_bus.handler, message: Service\Contract\Model\Order\Command\ChangeStatus }

    messagebus_command_order\ChangeAttributesHandler:
        class: Service\Contract\Model\Order\Handler\ChangeAttributesHandler
        arguments: ['@eventStore\OrderRepository']
        tags:
        - { name: contract_service_command_bus.handler, message: Service\Contract\Model\Order\Command\ChangeAttributes }

    messagebus_command_order\LockOrderHandler:
        class: Service\Contract\Model\Order\Handler\LockOrderHandler
        arguments: ['@eventStore\OrderRepository']
        tags:
        - { name: contract_service_command_bus.handler, message: Service\Contract\Model\Order\Command\LockOrder }

    messagebus_command_order\UnLockOrderHandler:
        class: Service\Contract\Model\Order\Handler\UnLockOrderHandler
        arguments: ['@eventStore\OrderRepository']
        tags:
        - { name: contract_service_command_bus.handler, message: Service\Contract\Model\Order\Command\UnLockOrder }

    #PROCESS MANAGERS FOR DEACTIVATING LINKED ORDERS AND LINKED OFFERS and etc.
