services:

#    message_factory:
#        class: AirSlate\Payment\Infrastructure\Messaging\Message\FQCNFactory

    contract_service_command_bus:
        class: Service\Infrastructure\Messaging\Bus\MessageBus
        public: true

    contract_service_event_bus:
        class: Service\Infrastructure\Messaging\Bus\MessageBus
        public: true