version: "3"

volumes:
  mongo:
#  mysql:
#  redis:
#  es:
#  phpmyadmin:

services:
  #######################################
  # Main Services
  #######################################
  app:
    build: .
    ports:
    - 10080:80
    - 10443:443
    volumes:
    - .:/app
#    - ./docker/log/:/var/log/pdffiller

  mongodb:
    image: mongo:latest
#    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    - MONGODB_USER="user"
    - MONGODB_PASS="pass"
    volumes:
    - mongo:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongoclient:
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    environment:
    - MONGO_URL=mongodb://mongodb:27017/grain_db
    depends_on:
    - mongodb
    volumes:
    - mongo:/data/db
    ports:
    - 3300:3000

#  mysql:
#    image: mysql:5.7.17
#    env_file:
#    - docker-compose.env
#    expose:
#    - 3306
#    ports:
#    - 13306:3306
#    volumes:
#    - mysql:/var/lib/mysql


  #######################################
  # Additional Services
  #######################################
#  redis:
#    image: redis
#    ports:
#    - 16379:6379
#    volumes:
#    - redis:/data


#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    env_file:
#    - docker-compose.env
#    depends_on:
#    - mysql
#    ports:
#    - 8001:80
#    volumes:
#    - phpmyadmin:/sessions